version: '3'

# Cline CLI Orchestration Taskfile
# Manages the interaction between Cline CLI and Kilo Code Agents

tasks:
  # --- Setup & Environment ---
  cline_cli.setup:
    desc: 'Setup agent orchestration environment'
    cmds:
      - mkdir -p .cline/logs .cline/backups
      - echo "Agent orchestration environment ready"
    silent: true

  cline_cli.update-prompts:
    desc: 'Update Cline prompt library'
    cmds:
      - |
        echo "Updating Cline prompt library..."
        curl -s https://cline.bot/prompts > .cline/prompts/latest.html || echo "Failed to download prompts"
        echo "Prompt library updated"

  # --- Core Orchestration Commands ---
  orch:
    desc: 'List available orchestration modes (Slash Command /orch)'
    cmds:
      - node .cline/scripts/cline-cli.js --orch

  orchplan:
    desc: 'Suggest next planned tasks (Slash Command /orchplan)'
    cmds:
      - node .cline/scripts/cline-cli.js --orchplan

  refine:
    desc: 'Optimizes a raw prompt using Meta-Prompting (Slash Command /refine)'
    vars:
      PROMPT: '{{.PROMPT}}'
    cmds:
      - node .cline/scripts/cline-cli.js --refine "$PROMPT"

  context:
    desc: 'Refreshes or Assembles Context (Slash Command /context)'
    vars:
      SCENARIO: "{{.SCENARIO | default 'default'}}"
    cmds:
      - node .cline/scripts/cline-cli.js --map --scenario "$SCENARIO"
      - echo "Context assembled for scenario: $SCENARIO"

  janitor:
    desc: 'Runs the Project Janitor agent to cleanup and archive'
    cmds:
      - task context SCENARIO=cleanup
      - task cline_cli.suggest AGENT_MODE=janitor-agent
      - echo "Run the above suggestion to start cleaning."

  # --- Agent Interaction ---
  cline_cli.suggest:
    desc: 'Get prompt suggestions for current phase (formerly agent.cline-suggest)'
    vars:
      CURRENT_PHASE: '{{.CURRENT_PHASE}}'
      CONTEXT: '{{.CONTEXT}}'
      AGENT_MODE: '{{.AGENT_MODE}}'
    cmds:
      - |
        echo "Getting prompt suggestions for phase: $CURRENT_PHASE"
        node .cline/scripts/cline-cli.js --phase "$CURRENT_PHASE" --context "$CONTEXT" --agent "$AGENT_MODE" > .cline/suggestions.json
        echo "Suggestions saved to .cline/suggestions.json"

  cline_cli.log:
    desc: 'Log agent interaction'
    vars:
      ID: '{{.ID}}'
      PROMPT: '{{.PROMPT}}'
    cmds:
      - echo "Logging interaction $ID"
      # (Simplified log command for brevity in this update)

  # --- Phase Management ---
  phase.start:
    desc: 'Start new development phase'
    vars:
      PHASE: '{{.PHASE}}'
      CONTEXT: '{{.CONTEXT}}'
    cmds:
      - |
        echo "Starting phase: $PHASE"
        echo "{\"phase\": \"$PHASE\", \"startTime\": \"$(date -u)\", \"context\": \"$CONTEXT\"}" > .cline/context/current-phase.json
        # Sync to Kilo via Symlink happens automatically now

  phase.setup:
    desc: 'Setup tasks for specific phase'
    vars:
      PHASE: '{{.PHASE}}'
    cmds:
      - |
        case "$PHASE" in
          "setup") task cline_cli.setup ;;
          "architecture") task cline_cli.suggest CURRENT_PHASE="architecture" AGENT_MODE="architect-orchestrator" ;;
          "implementation") task cline_cli.suggest CURRENT_PHASE="implementation" AGENT_MODE="architect-orchestrator" ;;
          "testing") task cline_cli.suggest CURRENT_PHASE="testing" AGENT_MODE="qa-engineer" ;;
          "deployment") task cline_cli.suggest CURRENT_PHASE="deployment" AGENT_MODE="devops-engineer" ;;
        esac

  # --- Aliases / Shortcuts ---
  suggest:
    cmds:
      - task cline_cli.suggest
